machines:
  - name: "dominaria"
    roles: 
      - "proxmox"
    networks: 
      - "infra"
      - "apps"
    cpus:
      - brand: "Intel i7-10700KF"
        cores: "20"
    memory: "64GB"
    nics:
      - name: enp6s0
        speed: 1GB
      - name: enp7s0f0
        speed: 1GB
      - name: enp7s0f1
        speed: 1GB
      - name: enp7s0f2
        speed: 1GB
      - name: enp7s0f3
        speed: 1GB
    disks: 
      ssd: 
        - brand: "Samsung 850 EVO"
          device: "sda"
          size: "250GB"
      nvme: 
        - brand: "Sabrant Rocket Q"
          size: "1TB"
          device: "nvme0n1"
      hdd:
        - size: "4TB"
          device: "sdb"
        - size: "4TB"
          device: "sdc"
  - name: "ravnica"
    roles: 
      - "proxmox"
    networks: 
      - "infra"
      - "apps"
    cpus:
      - brand: "AMD Ryzen 7 5800x"
        cores: "16"
    memory: "64GB"
    nics:
      - name: enp8s0
        speed: 1GB
      - name: enp9s0f0
        speed: 10GB
      - name: enp9s0f1
        speed: 10GB
    disks: 
      ssd: 
        - brand: "Kingston"
          size: "240GB"
          device: "sda"
      nvme: 
        - brand: "Silicon Power"
          size: "500GB"
          device: "nvme0n1"