hosts:
  - name: kaldheim
    mac: 48:21:0B:59:A8:FC
    brand: nuc
    model: NUC13ANHi5
    cores: 12
    memory: 64
    disks:
      - name: sda
        size: 256
        type: ssd
      - name: nvme0n1
        size: 1000
        type: nvme
  - name: eldraine
    mac: 00:00:00:00:00:00
    brand: nuc
    model: NUC13ANHi5
    cores: 12
    memory: 64
    disks:
      - name: sda
        size: 256
        type: ssd
      - name: nvme0n1
        size: 1000
        type: nvme
  - name: theros
    mac: 00:00:00:00:00:00
    brand: nuc
    model: NUC13ANHi5
    cores: 12
    memory: 64
    disks:
      - name: sda
        size: 256
        type: ssd
      - name: nvme0n1
        size: 1000
        type: nvme
