apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: connect
    app.kubernetes.io/instance: 1password-connect-helm-c8c1b192
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.2
    helm.sh/chart: connect-1.14.0
  name: onepassword-connect
  namespace: onepassword-connect
spec:
  ports:
    - name: connect-sync
      port: 8081
    - name: connect-api-https
      port: 8443
  selector:
    app: onepassword-connect
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: connect
    app.kubernetes.io/instance: 1password-connect-helm-c8c1b192
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.2
    helm.sh/chart: connect-1.14.0
  name: onepassword-connect
  namespace: onepassword-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onepassword-connect
  template:
    metadata:
      labels:
        app: onepassword-connect
        app.kubernetes.io/component: connect
        version: 1.7.2
    spec:
      containers:
        - env:
            - name: OP_SESSION
              valueFrom:
                secretKeyRef:
                  key: 1password-credentials.json
                  name: op-credentials
            - name: OP_BUS_PORT
              value: "11220"
            - name: OP_BUS_PEERS
              value: localhost:11221
            - name: OP_TLS_CERT_FILE
              value: /home/opuser/.op/certs/tls.crt
            - name: OP_TLS_KEY_FILE
              value: /home/opuser/.op/certs/tls.key
            - name: OP_HTTPS_PORT
              value: "8443"
            - name: OP_LOG_LEVEL
              value: info
          image: 1password/connect-api:1.7.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /heartbeat
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 30
          name: connect-api
          readinessProbe:
            httpGet:
              path: /health
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 15
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 999
            runAsUser: 999
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
            - mountPath: /home/opuser/.op/certs
              name: tls-cert
        - env:
            - name: OP_HTTP_PORT
              value: "8081"
            - name: OP_SESSION
              valueFrom:
                secretKeyRef:
                  key: 1password-credentials.json
                  name: op-credentials
            - name: OP_BUS_PORT
              value: "11221"
            - name: OP_BUS_PEERS
              value: localhost:11220
            - name: OP_LOG_LEVEL
              value: info
          image: 1password/connect-sync:1.7.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /heartbeat
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
          name: connect-sync
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 999
            runAsUser: 999
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
      tolerations: []
      volumes:
        - emptyDir: {}
          name: shared-data
        - name: credentials
          secret:
            secretName: op-credentials
        - name: tls-cert
          secret:
            secretName: op-connect-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: prod
    cert-manager.io/duration: 2160h
    cert-manager.io/renew-before: 360h
  labels:
    app.kubernetes.io/instance: 1password-connect-helm-c8c1b192
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    helm.sh/chart: connect-1.14.0
  name: connect
  namespace: onepassword-connect
spec:
  ingressClassName: nginx
  rules:
    - host: connect.us-drig-1.drigs.org
      http:
        paths:
          - backend:
              service:
                name: onepassword-connect
                port:
                  number: 8443
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - connect.us-drig-1.drigs.org
      secretName: op-connect-tls
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-weight: "1"
  labels:
    app.kubernetes.io/instance: 1password-connect-helm-c8c1b192
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.2
    helm.sh/chart: connect-1.14.0
  name: 1password-connect-helm-c8c1b192-health-check
  namespace: onepassword-connect
spec:
  containers:
    - command:
        - curl
        - https://onepassword-connect:8443/health
      image: curlimages/curl
      name: curl
  restartPolicy: Never
