apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-charts
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/kubernetes/charts
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
